// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfiwcejabijeiaidcdur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaXdjZWphYmlqZWlhaWRjZHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODIzNjEsImV4cCI6MjA4NDc1ODM2MX0.h9QOGmLV4RNuSjZ24NKVfhDxrnnFph4tNKSd6ZRIQDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});